name: Inputs and Outputs

on: 
    workflow_dispatch:
        inputs:
            dry-run: 
                type: boolean
                default: false
                description: 'Skip deployment and only print build output'
            target: 
                type: string
                description: 'Which environment the workflow will target'
                required: true
            tags:
                type: choice
                description: 'Release from which to build and deploy'
                options:
                    - v3
                    - v2
                    - v1
                default: 'v3'
                required: false
            build-status:
                type: choice
                description: 'Choose the build status for the demo'
                default: success
                options:
                    - failure
                    - success

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Print GITHUB_OUTPUT path
              run:echo "GITHUB_OUTPUT path: $GITHUB_OUTPUT"

            - name: Build
              id: build
              run: |
                  echo "tag=${{ inputs.tag }}" >> $GITHUB_OUTPUT
                  echo "status=${{ inputs.build-status }}" >> $GITHUB_OUTPUT
    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: |
            needs.build.result == 'success' &&
            inputs.dry-run == false &&
            needs.build.outputs.status == 'success'
        environment: ${{ inputs.target }}
        steps:
            - name: Deploy
              run: |
                echo "Deploying to '${{ inputs.target }}' using tag '${{ inputs.tag }}'"
