name: Inputs and Outputs

on:
  workflow_dispatch:
    inputs:
      dry-run: 
        type: boolean
        description: 'Skip deployment and only print build output'
      target: 
        type: string
        description: 'Which environment the workflow will target'
        required: true
      tags:
        type: choice
        description: 'Release from which to build and deploy'
        options:
          - v3
          - v2
          - v1
        default: 'v3'
      build-status:
        type: choice
        description: 'Choose the build status for the demo'
        default: success
        options:
          - failure
          - success

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.set-status.outputs.status }}
      tag: ${{ steps.set-status.outputs.tag }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: |
          echo "GITHUB_OUTPUT path: $GITHUB_OUTPUT"

      - name: Set Build Outputs
        id: set-status
        run: |
          echo "status=${{ inputs.build-status }}" >> $GITHUB_OUTPUT
          echo "tag=${{ inputs.tags }}" >> $GITHUB_OUTPUT

      - name: Debug outputs
        run: |
          echo "Build Status: ${{ inputs.build-status }}"
          echo "Tag: ${{ inputs.tags }}"
          echo "Tag: ${{ inputs.dry-run }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ inputs.build-status == 'success' && inputs.dry-run == false }}
    environment: ${{ inputs.target }}
    steps:
      - name: Debug Inputs and Outputs
        run: |
          echo "Build Output Status: ${{ needs.build.outputs.status }}"
          echo "Build Output Tag: ${{ needs.build.outputs.tag }}"
          echo "Input Dry Run: ${{ inputs.dry-run }}"

      - name: Deploy
        run: |
          echo "Deploying to '${{ inputs.target }}' using tag '${{ needs.build.outputs.tag }}'"
